### PR TITLE
Made models be ids for better Swift compatibility

### PR DESCRIPTION
**Pull request by mglidden**
Also updated project settings for example project (including new Xcode 7 default settings). If those cause issues in Xcode 6, I'll remove them from this commit.

### CODE REVIEW

**Comment by benasher44** [comment]
@mglidden looks good! I tested locally, and everything appears to be in good shape. Thanks for doing this!

**Comment by mglidden** [comment]
Thanks! Can you also push a v1.0.3 tag? CocoaPods can't be updated without it

**Comment by benasher44** [comment]
@mglidden woops! Great point. Going to do that now.

**Comment by benasher44** [comment]
@mglidden Tags are pushed. Just grappling with some errors locally in trying to push the podspec

**Comment by mglidden** [comment]
I already pushed the podspec :)

**Comment by benasher44** [comment]
Oh. Ha! Nice work.

**Pull request merged**
